name: editable
description: A highly customizable, editable data table (spreadsheet) package for Flutter projects.
version: 2.0.0
homepage: https://github.com/godilite/editable

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: '>=3.32.2'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true